In [1]:
import torch
import torchmetrics

In [2]:
metric = torchmetrics.Accuracy()

n_batches = 3
for i in range(n_batches):
    preds1 = torch.randn(10, 5).softmax(dim=-1)
    target1 = torch.randint(5, (10,))

    acc1 = metric(preds1, target1)

    print(f"Accuracy on batch {i}: {acc1}")

    

Accuracy on batch 0: 0.20000000298023224
Accuracy on batch 1: 0.30000001192092896
Accuracy on batch 2: 0.30000001192092896


In [3]:
preds1

tensor([[0.1042, 0.6140, 0.0487, 0.1160, 0.1170],
        [0.1121, 0.1124, 0.1121, 0.4814, 0.1821],
        [0.1753, 0.6374, 0.0412, 0.0193, 0.1268],
        [0.0671, 0.0990, 0.6610, 0.0636, 0.1093],
        [0.2337, 0.5695, 0.0664, 0.0528, 0.0775],
        [0.2337, 0.0796, 0.4169, 0.2372, 0.0326],
        [0.1852, 0.1399, 0.3900, 0.2022, 0.0828],
        [0.3435, 0.1184, 0.1105, 0.0401, 0.3875],
        [0.5711, 0.0265, 0.0566, 0.2816, 0.0642],
        [0.3920, 0.1390, 0.1564, 0.2516, 0.0610]])

In [4]:
target1

tensor([2, 2, 2, 2, 3, 2, 4, 4, 3, 4])

In [8]:
# total accuracy over all training batches
metric.compute()

tensor(0.3000)

In [10]:
print(metric)

Accuracy()


In [9]:
torch.cuda.is_available()

True

In [5]:
a = torch.randn(4, 5)
a

tensor([[-1.3470e+00,  1.2379e+00, -6.6805e-02,  3.4034e-01,  6.5314e-01],
        [ 5.7096e-01, -7.9748e-01,  7.1379e-02,  1.5989e-05, -1.3664e+00],
        [ 1.0294e+00,  5.7142e-01, -2.0712e-01,  4.8888e-01, -9.4706e-01],
        [ 1.6278e+00, -3.3836e-02, -9.9810e-01,  9.2007e-01, -9.6157e-02]])

In [6]:
a.softmax(-1)

tensor([[0.0326, 0.4326, 0.1174, 0.1763, 0.2411],
        [0.3890, 0.0990, 0.2361, 0.2198, 0.0561],
        [0.3782, 0.2393, 0.1098, 0.2203, 0.0524],
        [0.5172, 0.0982, 0.0374, 0.2549, 0.0923]])

In [7]:
0.0326+ 0.4326+ 0.1174+ 0.1763+ 0.2411

1.0

In [ ]:
import torch

logits = torch.randn(6,10) # [B, vocab_size]
logits

In [1]:
import torch
from torchmetrics import Accuracy

In [6]:
target = torch.tensor([0, 1,2,3])
preds = torch.tensor([2, 0,0,3])
accuracy = Accuracy()
accuracy(preds, target)

tensor(0.2500)

In [13]:
target = torch.tensor([0, 1, 2])
preds = torch.tensor([[1, 0.9, 0], [0.3, 0.9, 0.6], [0.2, 0.5, 0.3]])
preds

tensor([[1.0000, 0.9000, 0.0000],
        [0.3000, 0.9000, 0.6000],
        [0.2000, 0.5000, 0.3000]])

In [14]:
accuracy = Accuracy(top_k=1)
accuracy(preds, target)

tensor(0.6667)

Accuracy 的输入可以是预测的值，也可以是预测的 logits

In [1]:
from torchmetrics import MaxMetric

metric = MaxMetric()
metric.update(1)

In [2]:
metric

MaxMetric()

In [3]:
metric.update(10)

In [4]:
metric.update(3)

In [5]:
metric.compute()

tensor(10.)