如果我们的 Sentence = I hate this filem , embed_dim 是 5
那么 首先我们得到的是  [4, 5] 的 Tensor

如果一个 filter that covers two words at a time 那么 它的 size 是 2*5

绝大部分情况下， the width of the filter equals the width of the image

那么我们的输出 是一个列向量，长度等于 input sentence - filter 的长度 + 1

filter 的大小：[x，embed_dim], x 为自定义值，表示我们将同时考虑多少个单词


最后，我们使用 pooling / max pooling 策略

如选取的是 max, 相应的 idea 是 the maximum value is the most important feature for determining the sentiment of the review

conv2d:

in_channels: 对 text 而言是 1

out_channels: filters 的数量

kernel_size： the size of the filters -> [n, emb_dim]

对于 1D conv1d: embed_dim 是 filter 的 depth, the number of tokens in the sentence is the width

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F



在 LEAM 中，filter 的数量是 num_label, 
kernel_size = 55, padding = same
activation =  relu

In [2]:
x = torch.randn(4, 5, 100) # [B, S, E]
cnn_t = nn.Conv2d(1, 100, (3, 100))
cnn_tx = cnn_t(x.unsqueeze(1))
cnn_tx.shape

torch.Size([4, 100, 3, 1])

In [4]:
cnn_tx.max(2)[0]

tensor([[[ 8.4313e-01],
         [ 9.9337e-01],
         [-1.8493e-02],
         [ 1.2279e+00],
         [ 1.3368e+00],
         [-1.6008e-01],
         [ 2.4041e-01],
         [ 2.7624e-01],
         [ 9.7933e-01],
         [-2.9617e-01],
         [ 1.3381e-01],
         [-9.7418e-02],
         [ 4.2381e-02],
         [ 7.6695e-01],
         [ 9.5538e-01],
         [-2.8589e-02],
         [ 6.7862e-01],
         [ 8.4985e-01],
         [-6.6346e-01],
         [ 1.6341e-01],
         [ 8.3375e-01],
         [ 1.2506e-01],
         [ 1.5167e-01],
         [ 3.8805e-01],
         [ 1.0917e+00],
         [ 2.8610e-02],
         [ 4.3179e-01],
         [ 4.3955e-01],
         [ 8.2196e-01],
         [ 1.9083e-01],
         [ 5.0120e-01],
         [ 7.4731e-01],
         [ 7.6633e-01],
         [ 7.4243e-01],
         [ 6.9212e-01],
         [ 9.1723e-01],
         [ 1.9993e-01],
         [ 5.2155e-01],
         [ 1.1931e-01],
         [ 8.3650e-01],
         [ 3.5100e-01],
         [ 6.532

In [64]:
embedding_dim = 60

filter_size = 3
n_filters = 100

embedding = nn.Embedding(10, embedding_dim)

x =  torch.LongTensor([[1,2,6,4,5],[4,7,3,2,9]])
embedded = embedding(x) # [B, src_len, emb_dim]
embedded = embedded.unsqueeze(1) # [B, 1, S, D]

B = 3
S = 4
num_class = 5

G = torch.rand(B, S, 10)

#conv_1 = nn.Conv2d(in_channels= 1, out_channels= n_filters, kernel_size=(filter_size, embedding_dim))
# emb_x = conv_1(embedded)
# emb_x.shape

conv_same = nn.Conv2d(in_channels=1, out_channels=num_class, kernel_size=(55, 55), padding="same")

same_x = conv_same(G.unsqueeze(1))
same_x.shape

torch.Size([3, 5, 4, 10])

In [13]:
poolo = F.max_pool1d(xm,3)
poolo

tensor([[[0.4408],
         [0.6337],
         [0.7550],
         [0.9696],
         [0.5644]],

        [[0.5250],
         [0.6957],
         [0.3781],
         [0.7134],
         [0.6775]]])

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
x = torch.rand(3, 1,10, 4)
#x = F.pad(x, (0, 0, 2, 1))
x.shape

torch.Size([3, 1, 10, 4])

In [21]:
nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(1, 1), padding='same')(x).shape

torch.Size([3, 1, 10, 4])

In [2]:
print(torch.__version__)

1.10.0+cu102


In [17]:
x = torch.rand(5, 3, 6, 3)

x.shape

torch.Size([5, 3, 6, 3])

In [19]:
x.max(1).values.shape # 选择 filter 的最大值，沿着这一维度取最大值

torch.Size([5, 6, 3])

In [33]:
n_class = 6
input = torch.randn(3,5,4,n_class)
input

tensor([[[[ 1.1557e+00, -1.1023e+00, -7.3791e-03,  8.7132e-01,  3.7681e-01,
            7.6529e-01],
          [ 1.4153e+00, -1.3076e+00,  3.8974e-02,  5.0125e-01,  1.4715e+00,
            8.5850e-01],
          [-3.5332e-01,  2.5438e+00, -1.0984e+00, -7.9099e-01,  7.8507e-01,
            3.1143e-01],
          [-1.2961e+00, -1.6746e-01,  1.1019e+00,  4.9009e-01, -1.3292e+00,
           -3.9070e-01]],

         [[-4.3099e-01,  9.6011e-02,  3.5988e-01, -2.1541e+00, -5.9923e-01,
           -1.3836e-01],
          [ 1.6524e+00,  1.1419e+00, -2.2302e-01,  1.9284e-01, -1.2447e+00,
           -6.7204e-02],
          [-2.8756e-01,  7.2448e-01,  1.9918e-01,  2.9273e+00,  1.5029e+00,
           -1.0739e+00],
          [ 5.7187e-01,  7.5720e-01,  2.0876e-01, -2.1813e-01, -1.4246e+00,
            1.4102e+00]],

         [[-4.0107e-01,  5.5928e-01,  1.8372e+00, -8.9201e-01, -2.1774e+00,
            7.4511e-01],
          [ 9.3565e-01,  6.0112e-02,  8.9345e-01,  5.2579e-02, -6.2483e-01,
           

In [34]:
m = nn.MaxPool2d(kernel_size=(1,n_class))
output = m(input)
output.shape

torch.Size([3, 5, 4, 1])

In [2]:
b = torch.Tensor([[[3,2,4,5,1],[10,2,12,11,9],[1,12,9,10,6]],[[1,2,6,4,5],[4,7,3,2,9], [0, 32, 19, 3, 2]]])
b.shape

torch.Size([2, 3, 5])

In [3]:
b

tensor([[[ 3.,  2.,  4.,  5.,  1.],
         [10.,  2., 12., 11.,  9.],
         [ 1., 12.,  9., 10.,  6.]],

        [[ 1.,  2.,  6.,  4.,  5.],
         [ 4.,  7.,  3.,  2.,  9.],
         [ 0., 32., 19.,  3.,  2.]]])

In [5]:
9.1094e-04 + 9.9897e-01 + 1.2328e-04

1.00000422

In [6]:
b1 = F.softmax(b, dim=1)
b1.shape

torch.Size([2, 3, 5])

In [7]:
x = torch.rand(3, 1, 4, 100)
cnn1 = nn.Conv2d(1, 100, (3, 100))
cnnx = cnn1(x)
cnnx.shape

torch.Size([3, 100, 2, 1])

In [30]:
x=torch.rand(4, 2, 3)
x

tensor([[[0.6260, 0.2915, 0.7293],
         [0.7135, 0.5291, 0.5174]],

        [[0.3214, 0.1814, 0.8773],
         [0.0352, 0.8681, 0.5545]],

        [[0.6144, 0.0010, 0.7276],
         [0.4060, 0.2655, 0.9875]],

        [[0.1321, 0.9080, 0.0479],
         [0.5531, 0.5876, 0.7831]]])

In [31]:
xa = torch.sum(x, dim=1)
xa.shape

torch.Size([4, 3])

In [34]:
xa

tensor([[1.3395, 0.8206, 1.2466],
        [0.3566, 1.0495, 1.4318],
        [1.0204, 0.2666, 1.7151],
        [0.6852, 1.4956, 0.8310]])

In [35]:
xa + 100 

tensor([[101.3395, 100.8206, 101.2466],
        [100.3566, 101.0495, 101.4318],
        [101.0204, 100.2666, 101.7151],
        [100.6852, 101.4956, 100.8310]])

In [25]:
pooled

tensor([[[0.7691],
         [0.9947]],

        [[0.8548],
         [0.6517]],

        [[0.6328],
         [0.8889]],

        [[0.9935],
         [0.9005]]])

In [27]:
att = torch.rand(3,4)
att

tensor([[0.8926, 0.4268, 0.2696, 0.9474],
        [0.5629, 0.9080, 0.3842, 0.8829],
        [0.3371, 0.6865, 0.8198, 0.5430]])

In [28]:
F.softmax(att, dim=1)

tensor([[0.3105, 0.1949, 0.1666, 0.3280],
        [0.2162, 0.3053, 0.1808, 0.2977],
        [0.1898, 0.2693, 0.3076, 0.2333]])

In [29]:
0.3105+ 0.1949+ 0.1666+ 0.3280

1.0

In [3]:
batch_size = 3
seq_len   = 4 

num_class = 5

G = torch.randn(batch_size, seq_len, num_class)
cnn1 = nn.Conv1d(in_channels= num_class, out_channels= num_class, kernel_size= 3, padding='same')

In [5]:
G.shape

torch.Size([3, 4, 5])

In [6]:
cnn1

Conv1d(5, 5, kernel_size=(3,), stride=(1,), padding=same)

In [8]:
G = G.permute(0, 2, 1)  # 输入要修改为 batch_size, embedding_size, text_len
out = cnn1(G)
out.shape

torch.Size([3, 5, 4])

对于文本数据， filter 不在横向滑动，仅仅是向下移动